### ISSUE TITLE
Progress report of term project

### ISSUE THREAD

**Issue by shengwen-tw** [yungyuc/nsdhw_20au#116]
Progress report of [libqpsolver](https://github.com/shengwen-tw/libqpsolver)

1. Finished writing the main program
2. Finished writing the unit test program for testing numerical solver
3. Integration of GitHub action

Ongoing:
1. Writing the unit test program for Intel MKL wrappers
2. Testing on main program

**Comment by yungyuc** [comment]
@shengwen-tw could you file this issue in [the project you are working on](https://github.com/shengwen-tw/libqpsolver), and tag me there?  This repository is for the course notes, not a specific project.
