### ISSUE TITLE
Questions about hw3

### ISSUE THREAD

**Issue by Naetw** [yungyuc/nsdhw_20au#54]
1. The condition "20% faster" is against the situation that matrix size is larger than or equal to `1000x1000`, right? If so, do I have to care about the unit test in `validate.py` which uses `500x500` as the matrix size?
2. I’m not sure I understand what "`make test` should run the same unit tests" in Section "Additional notes on grading" means. Does it mean that I should write another test script which should be the same as the test written in `validate.py`?
3. Function `benchmark()` in `validate.py` doesn't compare tiling version with mkl version. Is that purposed?
4. The sentence "The format of performance.txt can be any. Just make it reasonable." looks like that we need to write our own `performance.txt`. But, if `validate.py` runs well (our own test script would be run first), our `performance.txt` would be overwritten by function `benchmark()`. Do we really have to output `performance.txt`?

Sorry for a bit late questions.

**Comment by yungyuc** [comment]
Answers:

1. Correct, it's against the `1000 x 1000` matrix.

2. `make test` should run the unit tests that you write.  You may or may not duplicate the tests in `validate.py`.  If you only write the tests already in `validate.py`, it misses the point of writing the tests, and the grader should take that into account.

3. Yes, you should provide your `performance.txt`.  It should be useful in your own code development.

No need to say sorry.  Please reopen the issue if you have further questions or comments.
